### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by areeb-gsoftconsulting** [capacitor-community/text-to-speech#102]
**Plugin version:**

version-->     

"@capacitor-community/text-to-speech": "^3.0.0",
"react": "^18.2.0",
 "@ionic/react": "^6.0.0",

**Platform(s):**

crashing on both Android and IOS, using Ionic React

**Current behavior:**
After installing this plugin and after following all the steps to make it run, finally, when I hit the command to run on Android or Ios, it crashes, 

ionic capacitor run android -l --external
? Which device would you like to target? Xiaomi M2101K7AG (c2138604)
> capacitor sync android
[capacitor] ✔ Copying web assets from build to android/app/src/main/assets/public in 150.07ms
[capacitor] ✔ Creating capacitor.config.json in android/app/src/main/assets in 2.11ms
[capacitor] ✔ copy android in 189.94ms
[capacitor] ✔ Updating Android plugins in 27.15ms
[capacitor] [info] Found 4 Capacitor plugins for android:
[capacitor]        @capacitor-community/text-to-speech@3.0.0
[capacitor]        @capacitor/camera@4.1.5
[capacitor]        @capacitor/filesystem@4.1.5
[capacitor]        @capacitor/preferences@4.0.2
[capacitor] ✔ update android in 143.79ms
[capacitor] [info] Sync finished in 0.343s
> react-scripts start
[react-scripts] Attempting to bind to HOST environment variable: 0.0.0.0
[react-scripts] If this was unintentional, check that you haven't mistakenly set it in your shell.
[react-scripts] Learn more here: https://cra.link/advanced-config
[react-scripts] (node:2480) [DEP_WEBPACK_DEV_SERVER_ON_AFTER_SETUP_MIDDLEWARE] DeprecationWarning: 'onAfterSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
[react-scripts] (Use `node --trace-deprecation ...` to show where the warning was created)
[react-scripts] (node:2480) [DEP_WEBPACK_DEV_SERVER_ON_BEFORE_SETUP_MIDDLEWARE] DeprecationWarning: 'onBeforeSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
[react-scripts] Starting the development server...
[react-scripts] 
[react-scripts] You can now view photo-gallery-capacitor-react in the browser.
[react-scripts]   Local:            http://localhost:8100
[react-scripts]   On Your Network:  http://192.168.1.13:8100
[react-scripts] Note that the development build is not optimized.
[react-scripts] To create a production build, use yarn build.

[INFO] Development server running!
       
       Local: http://localhost:8100
       External: http://192.168.1.13:8100
       
       Use Ctrl+C to quit this process

[react-scripts] webpack compiled successfully
> capacitor run android --no-sync --target c2138604
[react-scripts] Files successfully emitted, waiting for typecheck results...
[react-scripts] Issues checking in progress...
[react-scripts] No issues found.
[capacitor] ✖ Running Gradle build - failed!
[capacitor] [error] 
[capacitor]         > Configure project :app
[capacitor]         google-services.json not found, google-services plugin not applied. Push Notifications won't work
[capacitor]         WARNING:Using flatDir should be avoided because it doesn't support any meta-data formats.
[capacitor]         
[capacitor]         > Configure project :capacitor-cordova-android-plugins
[capacitor]         WARNING:Using flatDir should be avoided because it doesn't support any meta-data formats.
[capacitor]         
[capacitor]         > Task :app:preBuild UP-TO-DATE
[capacitor]         > Task :app:preDebugBuild UP-TO-DATE
[capacitor]         > Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
[capacitor]         > Task :capacitor-android:preBuild UP-TO-DATE
[capacitor]         > Task :capacitor-android:preDebugBuild UP-TO-DATE
[capacitor]         > Task :capacitor-android:compileDebugAidl NO-SOURCE
[capacitor]         > Task :capacitor-camera:preBuild UP-TO-DATE
[capacitor]         > Task :capacitor-camera:preDebugBuild UP-TO-DATE
[capacitor]         > Task :capacitor-camera:compileDebugAidl NO-SOURCE
[capacitor]         > Task :capacitor-community-text-to-speech:preBuild UP-TO-DATE
[capacitor]         > Task :capacitor-community-text-to-speech:preDebugBuild UP-TO-DATE
[capacitor]         > Task :capacitor-community-text-to-speech:compileDebugAidl NO-SOURCE
[capacitor]         > Task :capacitor-cordova-android-plugins:preBuild UP-TO-DATE
[capacitor]         > Task :capacitor-cordova-android-plugins:preDebugBuild UP-TO-DATE
[capacitor]         > Task :capacitor-cordova-android-plugins:compileDebugAidl NO-SOURCE
[capacitor]         > Task :capacitor-filesystem:preBuild UP-TO-DATE
[capacitor]         > Task :capacitor-filesystem:preDebugBuild UP-TO-DATE
[capacitor]         > Task :capacitor-filesystem:compileDebugAidl NO-SOURCE
[capacitor]         > Task :capacitor-preferences:preBuild UP-TO-DATE
[capacitor]         > Task :capacitor-preferences:preDebugBuild UP-TO-DATE
[capacitor]         > Task :capacitor-preferences:compileDebugAidl NO-SOURCE
[capacitor]         > Task :app:compileDebugAidl NO-SOURCE
[capacitor]         > Task :capacitor-android:packageDebugRenderscript NO-SOURCE
[capacitor]         > Task :capacitor-camera:packageDebugRenderscript NO-SOURCE
[capacitor]         > Task :capacitor-community-text-to-speech:packageDebugRenderscript NO-SOURCE
[capacitor]         > Task :capacitor-cordova-android-plugins:packageDebugRenderscript NO-SOURCE
[capacitor]         > Task :capacitor-filesystem:packageDebugRenderscript NO-SOURCE
[capacitor]         > Task :capacitor-preferences:packageDebugRenderscript NO-SOURCE
[capacitor]         > Task :app:compileDebugRenderscript NO-SOURCE
[capacitor]         > Task :app:generateDebugBuildConfig UP-TO-DATE
[capacitor]         > Task :app:javaPreCompileDebug UP-TO-DATE
[capacitor]         > Task :capacitor-android:writeDebugAarMetadata UP-TO-DATE
[capacitor]         > Task :capacitor-camera:writeDebugAarMetadata UP-TO-DATE
[capacitor]         > Task :capacitor-community-text-to-speech:writeDebugAarMetadata UP-TO-DATE
[capacitor]         > Task :capacitor-filesystem:writeDebugAarMetadata UP-TO-DATE
[capacitor]         > Task :capacitor-cordova-android-plugins:writeDebugAarMetadata
[capacitor]         > Task :capacitor-preferences:writeDebugAarMetadata UP-TO-DATE
[capacitor]         > Task :app:checkDebugAarMetadata UP-TO-DATE
[capacitor]         > Task :app:generateDebugResValues UP-TO-DATE
[capacitor]         > Task :app:generateDebugResources UP-TO-DATE
[capacitor]         > Task :capacitor-android:compileDebugRenderscript NO-SOURCE
[capacitor]         > Task :capacitor-android:generateDebugResValues UP-TO-DATE
[capacitor]         > Task :capacitor-android:generateDebugResources UP-TO-DATE
[capacitor]         > Task :capacitor-android:packageDebugResources UP-TO-DATE
[capacitor]         > Task :capacitor-camera:compileDebugRenderscript NO-SOURCE
[capacitor]         > Task :capacitor-camera:generateDebugResValues UP-TO-DATE
[capacitor]         > Task :capacitor-camera:generateDebugResources UP-TO-DATE
[capacitor]         > Task :capacitor-camera:packageDebugResources UP-TO-DATE
[capacitor]         > Task :capacitor-community-text-to-speech:compileDebugRenderscript NO-SOURCE
[capacitor]         > Task :capacitor-community-text-to-speech:generateDebugResValues UP-TO-DATE
[capacitor]         > Task :capacitor-community-text-to-speech:generateDebugResources UP-TO-DATE
[capacitor]         > Task :capacitor-community-text-to-speech:packageDebugResources UP-TO-DATE
[capacitor]         > Task :capacitor-cordova-android-plugins:compileDebugRenderscript NO-SOURCE
[capacitor]         > Task :capacitor-cordova-android-plugins:generateDebugResValues
[capacitor]         > Task :capacitor-cordova-android-plugins:generateDebugResources
[capacitor]         > Task :capacitor-cordova-android-plugins:packageDebugResources
[capacitor]         > Task :capacitor-filesystem:compileDebugRenderscript NO-SOURCE
[capacitor]         > Task :capacitor-filesystem:generateDebugResValues UP-TO-DATE
[capacitor]         > Task :capacitor-filesystem:generateDebugResources UP-TO-DATE
[capacitor]         > Task :capacitor-filesystem:packageDebugResources UP-TO-DATE
[capacitor]         > Task :capacitor-preferences:compileDebugRenderscript NO-SOURCE
[capacitor]         > Task :capacitor-preferences:generateDebugResValues UP-TO-DATE
[capacitor]         > Task :capacitor-preferences:generateDebugResources UP-TO-DATE
[capacitor]         > Task :capacitor-preferences:packageDebugResources UP-TO-DATE
[capacitor]         > Task :app:mergeDebugResources UP-TO-DATE
[capacitor]         > Task :app:mapDebugSourceSetPaths UP-TO-DATE
[capacitor]         > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[capacitor]         > Task :app:extractDeepLinksDebug UP-TO-DATE
[capacitor]         > Task :capacitor-android:extractDeepLinksDebug UP-TO-DATE
[capacitor]         > Task :capacitor-android:processDebugManifest UP-TO-DATE
[capacitor]         > Task :capacitor-camera:extractDeepLinksDebug UP-TO-DATE
[capacitor]         > Task :capacitor-camera:processDebugManifest UP-TO-DATE
[capacitor]         > Task :capacitor-community-text-to-speech:extractDeepLinksDebug UP-TO-DATE
[capacitor]         > Task :capacitor-community-text-to-speech:processDebugManifest UP-TO-DATE
[capacitor]         > Task :capacitor-cordova-android-plugins:extractDeepLinksDebug
[capacitor]         > Task :capacitor-filesystem:extractDeepLinksDebug UP-TO-DATE
[capacitor]         > Task :capacitor-filesystem:processDebugManifest UP-TO-DATE
[capacitor]         > Task :capacitor-preferences:extractDeepLinksDebug UP-TO-DATE
[capacitor]         > Task :capacitor-preferences:processDebugManifest UP-TO-DATE
[capacitor]         > Task :capacitor-android:compileDebugLibraryResources UP-TO-DATE
[capacitor]         > Task :capacitor-android:parseDebugLocalResources UP-TO-DATE
[capacitor]         > Task :capacitor-cordova-android-plugins:processDebugManifest
[capacitor]         > Task :capacitor-android:generateDebugRFile UP-TO-DATE
[capacitor]         > Task :capacitor-camera:compileDebugLibraryResources UP-TO-DATE
[capacitor]         > Task :capacitor-camera:parseDebugLocalResources UP-TO-DATE
[capacitor]         > Task :capacitor-camera:generateDebugRFile UP-TO-DATE
[capacitor]         > Task :app:processDebugMainManifest UP-TO-DATE
[capacitor]         > Task :app:processDebugManifest UP-TO-DATE
[capacitor]         > Task :app:processDebugManifestForPackage UP-TO-DATE
[capacitor]         > Task :capacitor-community-text-to-speech:compileDebugLibraryResources UP-TO-DATE
[capacitor]         > Task :capacitor-community-text-to-speech:parseDebugLocalResources UP-TO-DATE
[capacitor]         > Task :capacitor-community-text-to-speech:generateDebugRFile UP-TO-DATE
[capacitor]         > Task :capacitor-cordova-android-plugins:compileDebugLibraryResources
[capacitor]         > Task :capacitor-filesystem:compileDebugLibraryResources UP-TO-DATE
[capacitor]         > Task :capacitor-filesystem:parseDebugLocalResources UP-TO-DATE
[capacitor]         > Task :capacitor-cordova-android-plugins:parseDebugLocalResources
[capacitor]         > Task :capacitor-filesystem:generateDebugRFile UP-TO-DATE
[capacitor]         > Task :capacitor-preferences:compileDebugLibraryResources UP-TO-DATE
[capacitor]         > Task :capacitor-preferences:parseDebugLocalResources UP-TO-DATE
[capacitor]         > Task :capacitor-preferences:generateDebugRFile UP-TO-DATE
[capacitor]         > Task :capacitor-android:generateDebugBuildConfig UP-TO-DATE
[capacitor]         > Task :capacitor-android:javaPreCompileDebug UP-TO-DATE
[capacitor]         > Task :capacitor-android:compileDebugJavaWithJavac UP-TO-DATE
[capacitor]         > Task :capacitor-android:bundleLibCompileToJarDebug UP-TO-DATE
[capacitor]         > Task :capacitor-camera:generateDebugBuildConfig UP-TO-DATE
[capacitor]         > Task :capacitor-camera:javaPreCompileDebug UP-TO-DATE
[capacitor]         > Task :capacitor-cordova-android-plugins:generateDebugRFile
[capacitor]         > Task :capacitor-camera:compileDebugJavaWithJavac UP-TO-DATE
[capacitor]         > Task :capacitor-camera:bundleLibCompileToJarDebug UP-TO-DATE
[capacitor]         > Task :capacitor-community-text-to-speech:generateDebugBuildConfig UP-TO-DATE
[capacitor]         > Task :capacitor-community-text-to-speech:javaPreCompileDebug UP-TO-DATE
[capacitor]         > Task :capacitor-community-text-to-speech:compileDebugJavaWithJavac FAILED
[capacitor]         
[capacitor]         FAILURE: Build failed with an exception.
[capacitor]         
[capacitor]         * What went wrong:
[capacitor]         Execution failed for task ':capacitor-community-text-to-speech:compileDebugJavaWithJavac'.
[capacitor]         > error: invalid source release: 17
[capacitor]         
[capacitor]         * Try:
[capacitor]         > Run with --stacktrace option to get the stack trace.
[capacitor]         > Run with --info or --debug option to get more log output.
[capacitor]         > Run with --scan to get full insights.
[capacitor]         
[capacitor]         * Get more help at https://help.gradle.org
[capacitor]         
[capacitor]         BUILD FAILED in 1s
[capacitor]         70 actionable tasks: 9 executed, 61 up-to-date
[capacitor]         
[ERROR] An error occurred while running subprocess capacitor.
        
        capacitor run android --no-sync --target c2138604 exited with exit code
        1.
        
        Re-running this command with the --verbose flag may provide more
        information.

**Expected behavior:**
As I follow all the required steps, it should run properly and convert text to speech,

**NOTE**: I have even created a new bare ionic react app as a tabs starter template, also crashing in it.

**Steps to reproduce:**
Here are the steps to reproduce,
-> Create an ionic react app as a tabs starter template. 
-> yarn add @capacitor-community/text-to-speech
-> npx cap sync
-> ionic capacitor copy android
-> ionic capacitor run android -l --external

**Other information:**
I am using the Ionic react app with capacitor and, I was having issues in my app, then I created a new template and the same issue is reproducing on my end, and one thing more, I install this package with yarn because using npm it is not installed on my end. 

**Capacitor doctor:**

```
insert the output from `npx cap doctor` here

 npx cap doctor
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.0.4
  @capacitor/core: 5.0.4
  @capacitor/android: 5.0.4
  @capacitor/ios: 5.0.4

Installed Dependencies:

  @capacitor/cli: 4.8.0
  @capacitor/android: 4.8.0
  @capacitor/ios: 4.8.0
  @capacitor/core: 4.8.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

**Comment by robingenz** [comment]
Please make sure that you use Java 17 which is required for Capacitor 5.

**Comment by jcesarmobile** [comment]
version 3.0.0 of the plugin is for Capacitor 5, but you are still using Capacitor 4, as stated on the [breaking changes file](https://github.com/capacitor-community/text-to-speech/blob/master/CHANGELOG.md#300-2023-05-04)
Upgrade to Capacitor 5 or downgrade the plugin.
