### ISSUE TITLE
feat: onEnd event is required

### ISSUE THREAD

**Issue by subhankhalid402** [capacitor-community/text-to-speech#103]
**Is your feature request related to a problem? Please describe:**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by robingenz** [comment]
I am closing this issue because it is missing relevant information.
You already know when the `speak(...)` method is finished (if that's what you mean), because a Promise is returned, which only resolves when the operation is finished.
