### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by subhankhalid402** [capacitor-community/text-to-speech#108]
unable to run text to speech on amazon fire stick tv please help

**Comment by ecc521** [comment]
It's very possible that the Amazon Fire Stick TV simply doesn't support the tts API that this library needs. 
Can you provide an error message so that this can actually be looked at? I don't have an Amazon Fire Stick TV, so cannot debug this myself.

**Comment by robingenz** [comment]
I close this issue as not planned.
