### ISSUE TITLE
bug: stop() not working in IOS

### ISSUE THREAD

**Issue by tspvivek** [capacitor-community/text-to-speech#122]
**Plugin version:**
4.0.1

**Platform(s):**
IOS

**Current behavior:**
When stop() is called the playback is still continuing in IOS, but works well in android and Web.

**Expected behavior:**
Playback should have stopped immediately.

**Comment by tspvivek** [comment]
Sorry, Found what i am doing wrong. It seems like stop() is called when speak() is still in progress android throws exception, but IOS doesn't so need to handle that in my code.

**Comment by robingenz** [comment]
In this case i am closing this issue.
