### ISSUE TITLE
bug: Not yet initialized or not available on this device.

### ISSUE THREAD

**Issue by owencyc** [capacitor-community/text-to-speech#137]
**Plugin version:**

@capacitor-community/text-to-speech@5.0.0

**Platform(s):**

**Android**
device info
model: "PDA"
osVersion: 9
androidSDKVersion: 28
manufacturer: "alps"
webViewVersion: "105.0.5195.136"

**Current behavior:**

console error

**Expected behavior:**

no error,can speak

I would like to know the basic device requirements for using this plugin, including Android version, system components, etc.

**Steps to reproduce:**

**Related code:**

```
import { TextToSpeech } from '@capacitor-community/text-to-speech'

const speak = () => {
  setTimeout(async () => {
    await TextToSpeech.speak({
      text: 'hello world',
      lang: 'en-US',
      rate: 1.0,
      pitch: 1.0,
      volume: 1.0,
      category: 'ambient'
    })
    const languages = await TextToSpeech.getSupportedLanguages()
    const voices = await TextToSpeech.getSupportedVoices()
    console.log('支持的语言')
    console.log(languages)
    console.log('支持的人声')
    console.log(voices)
  })
}

speak()

```

**Other information:**

![e9154bbf36b42f3994bc5315e07ad50](https://github.com/user-attachments/assets/c9eb30cb-4834-4fd8-bc07-e92d6731fbb6)
![image](https://github.com/user-attachments/assets/fac561bb-57ac-446d-930f-9c72a54e6271)

**Capacitor doctor:**

```
   Capacitor Doctor   

Latest Dependencies:

  @capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/android: 6.1.2
  @capacitor/ios: 6.1.2

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/android: 6.1.2

[success] Android looking great! 👌
```

**Comment by robingenz** [comment]
Here you can find the implementation of the `isAvailable` method: https://github.com/capacitor-community/text-to-speech/blob/8ad38a57a4ff4d0d49a3b80b7321dd025953b110/android/src/main/java/com/getcapacitor/community/tts/TextToSpeech.java#L165

Since this does not seem to be a bug, but it looks like TTS is simply not available on your device, I am closing this issue.
