### ISSUE TITLE
Cant run on iOS

### ISSUE THREAD

**Issue by jeremyrajan** [capacitor-community/text-to-speech#2]
**Describe the bug**
When trying to sync before running iOS build. It gives me this error and eventually fails on Xcode as well.
![image](https://user-images.githubusercontent.com/2890683/85817935-f8cca400-b7a1-11ea-86aa-a36d5020d49a.png)

**To Reproduce**
Follow as readme

**Comment by priyankpat** [comment]
A new release [v0.2.0](https://github.com/capacitor-community/text-to-speech/releases/tag/v0.2.0) is now released with the fix. 

Sorry for the delay in reply. Leaving the issue open until you've tested it on your end.

**Comment by priyankpat** [comment]
Closing the issue as it's stale. Feel free to re-open if required.
