### ISSUE TITLE
feat: add support for `getSupportedVoices` on iOS

### ISSUE THREAD

**Issue by robingenz** [capacitor-community/text-to-speech#37]
**Is your feature request related to a problem? Please describe.**
`getSupportedVoices` should also be available on iOS.
Currently an empty array is returned.

**Describe the solution you'd like**
Add support for `getSupportedVoices` on iOS.

**Describe alternatives you've considered**
Mark as unsupported in docs.

**Comment by spasma** [comment]
I can help with this if this is unplanned at the moment, I've written this for my plugin cordova-plugin-tts-advanced (https://www.npmjs.com/package/cordova-plugin-tts-advanced)

**Comment by robingenz** [comment]
Hi, thank you. Any support is welcome. Just create a PR.

**Comment by RouR** [comment]
Any progress?

**Comment by ecc521** [comment]
Logically I see two options here:
1. Just use speechSynthesis on iOS
2. Implement the iOS voices using native APIs. 

The current behavior probably makes the least sense of the three - merely using the webview's speechSynthesis on iOS would expand the featureset of this plugin.

**Comment by ecc521** [comment]
PR submitted
