### ISSUE TITLE
bug: [iOS] not working in background

### ISSUE THREAD

**Issue by iLoveBug** [capacitor-community/text-to-speech#48]
**Describe the bug**
I switch the app to background, then the tts.speak does not work. I got the following error:

OSStatus error 561015905

021-03-14 00:17:52.947145+0800 App[6317:1761621] [AXTTSCommon] Failure starting audio queue alp!
2021-03-14 00:17:55.033473+0800 App[6317:1761621] [AXTTSCommon] _BeginSpeaking: couldn't begin playback

It seems some other guys is suffering the same problem.

Any ideas?

**Smartphone (please complete the following information):**

- Device: iPhone 12 mini
- OS: iOS 14.4

**Comment by robingenz** [comment]
Please provide the steps required to reproduce the error, including code example.
Which plugin version do you use?

**Comment by iLoveBug** [comment]
Sorry, It's not a bug. It is caused by my mistake. After set the category to playback, it works fine.
