### ISSUE TITLE
bug: window.speechSynthesis not found for Android

### ISSUE THREAD

**Issue by Volteris** [capacitor-community/text-to-speech#69]
For Android

`if ('speechSynthesis' in window) {
this.speechSynthesis = window.speechSynthesis;
}`

window.speechSynthesis doesn't exist.

I have this result in the developer console
` Uncaught (in promise) Error: Not supported on this device.`

Does anyone have the same behavior ?

**Comment by robingenz** [comment]
Thank you for your request.
It seems that the web implementation is used on Android. 
Make sure you have added the plugin correctly.
Please fill out the issue template correctly so I have all the information to help you.
