### ISSUE TITLE
Speak not working!

### ISSUE THREAD

**Issue by oke007** [capacitor-community/text-to-speech#7]
Plugin not working either on web or even in android devices. Getting error: 

ERROR Error: 
**Uncaught (in promise): TypeError: Failed to set the 'voice' property on 'SpeechSynthesisUtterance': The provided value is not of type 'SpeechSynthesisVoice'.**

Also installation commends are wrong:
it should be as per the NPM directory: **npm i @capacitor-community/text-to-speech**

**Comment by rafaellupo** [comment]
Same here!

**Comment by Vall98** [comment]
I had the same issue, and commenting the lines 40 to 42 in node_modules/@capacitor-community/text-to-speech/dist/esm/web.js worked for me.

**Comment by dwieeb** [comment]
@Vall98 would you be able to send a PR? 😊

**Comment by Noaber** [comment]
Looks like the project is dead ?

**Comment by Vall98** [comment]
Just opened #13

**Comment by Vall98** [comment]
Note that it only fix the issue on web. I'm getting an other error on Android, but I don't know if it's related:

"Cannot find a differ supporting object [Voice [Name: ... ]]"

**Comment by robingenz** [comment]
Fixed various bugs on Android and Web.
You can give it a try: `npm i @capacitor-community/text-to-speech@0.2.1-dev.65857f5` 
If you find bugs in this version, please create a new issue with detailed description and steps to reproduce (see issue template).
