### ISSUE TITLE
Msg: Uncaught (in promise) Speech Synthesizer is not yet initialized or supported.

### ISSUE THREAD

**Issue by leafiy** [capacitor-community/text-to-speech#8]
**Describe the bug**
Msg: Uncaught (in promise) Speech Synthesizer is not yet initialized or supported.

**To Reproduce**
1. When call speak()

![image](https://user-images.githubusercontent.com/870449/101265922-a39bb200-3785-11eb-9f48-7caed0ecbb13.png)

**Comment by robingenz** [comment]
Can you please provide more information about the device and OS?
