### ISSUE TITLE
bug: Weird voice on andriod

### ISSUE THREAD

**Issue by haysquareA** [capacitor-community/text-to-speech#83]
**Plugin version:**

Latest

**Platform(s):**

Andriod

**Current behavior:**

Sounding weird on android, not sounding like human

**Expected behavior:**

To sound like human

**Steps to reproduce:**

**Related code:**

```
export const readOutLoud = async (message) => {
    
        await TextToSpeech.speak({
          
          text: message,
          lang: 'en-GB',
          rate: 0.5,
          pitch: 9,
          volume: 10,
          category: 'ambient',
        });
      } 
      
  };
```

**Other information:**

**Capacitor doctor:**

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.1.0
  @capacitor/core: 4.1.0
  @capacitor/android: 4.1.0
  @capacitor/ios: 4.1.0

Installed Dependencies:

  @capacitor/core: 4.1.0
  @capacitor/android: 4.1.0
  @capacitor/cli: 4.1.0
  @capacitor/ios: 4.1.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

**Comment by robingenz** [comment]
The voice is from Android. The plugin has no impact on this. For this reason I am closing this issue. 
Please make sure that the locale is correct and exists on the device.

**Comment by haysquareA** [comment]
How can I change the voice on andriod

**Comment by robingenz** [comment]
It depends on the selected language (see lang property).
